### ISSUE TITLE
Feature Request: Touch files/folders after sync

### ISSUE THREAD

**Issue by ozzii** [stefankueng/CryptSync#103]
Hi,
I'm syncing from my NAS to and external HD attached to the same NAS.
Some of the synced files, from inside the same folder, have the source date/time and some have the date/time of the created .7z file.

Here is an example:
100802-113854.jpg.7z	5.5 MB	15/04/23 12:21:28
100803-083735.jpg.7z	5.6 MB	15/04/23 12:21:29
100803-083743.jpg.7z	5.6 MB	03/08/10 08:37:42
100803-083756.jpg.7z	5.7 MB	03/08/10 08:37:56
100803-083807.jpg.7z	5.4 MB	03/08/10 08:38:06
100807-184027.jpg.7z	5.1 MB	15/04/23 12:21:32
100813-150741.jpg.7z	4.7 MB	13/08/10 15:07:40
100813-150802.jpg.7z	1.2 MB	15/04/23 12:21:33
100813-150822.jpg.7z	4.4 MB	15/04/23 12:21:34

Can you add an option to keep the original date/time of the files/folders?

Thank you in advance.

**Comment by stefankueng** [comment]
the file dates of the encrypted files must be the one where it was created. Otherwise could storage syncs might fail.
