### ISSUE TITLE
Request to sync filename changes & file moves

### ISSUE THREAD

**Issue by vinnic62** [stefankueng/CryptSync#104]
Hello Stefan,

Can we have the option to sync when there's a change to a file or folder name?

Also, when a file is moved.

Thank you.

**Comment by stefankueng** [comment]
You see the button "run in background" in the main dialog?
Use it!

**Comment by vinnic62** [comment]
That's what I've been using. I works beautifully for any other changes to a file. However, it doesn't seem to detect when a file is moved or its name is changed.
