### ISSUE TITLE
Does the server need to be logged in with a user to have cryptsync work?

### ISSUE THREAD

**Issue by greavette** [stefankueng/CryptSync#106]
Hello,

I've been using cryptsync for a few years now. I'm using version 1.4.4.462.  I'm using it on Windows Server 2019 Standard edition.  We have a MS SQL database backup completed nightly and I use cryptsync to mirror our database backup folder with an another folder on our NAS.  I've noticed lately that if no one is logged into the server cryptsync does not run.  I need to log in to the server and select 'Run Now' in order to get a current sync.

Has something changed?  I would like to have cryptsnc run like a service where we don't need to have a user logged in so that our database backups are moved nighly.  Is there a way for me to confirm that cryptsync has been set up to run when a user is not logged in?  Something I can check perhaps.

Thank you in advance for any advice you can provide me.

**Comment by stefankueng** [comment]
I assume you have mapped the NAS to some drive letter.
This however is done when the user logs on. If no user is logged on, then the drives are not mapped.
