### ISSUE TITLE
What about cyrillic?

### ISSUE THREAD

**Issue by artromone** [stefankueng/CryptSync#107]

**Comment by stefankueng** [comment]
what about it?

**Comment by artromone** [comment]
07/03/23 00:16:54 : ERROR:   Failed to encrypt file "D:\tmp\Rena\1\вапвапва.md" to "D:\tmp\Rena\2\вапвапва.md.gpg"
07/03/23 00:16:54 : INFO:    encrypt file D:\tmp\Rena\1\цукцукцукцук to D:\tmp\Rena\2\цукцукцукцук.gpg
07/03/23 00:16:54 : ERROR:   Failed to encrypt file "D:\tmp\Rena\1\цукцукцукцук" to "D:\tmp\Rena\2\цукцукцукцук.gpg"
07/03/23 00:16:54 : INFO:    finished syncing folder orig "D:\tmp\Rena\1" with crypt "D:\tmp\Rena\2"

**Comment by artromone** [comment]
When I use Latin it works

**Comment by stefankueng** [comment]
Well, you're using gpg. CryptSync calls gpg with the proper paths. If gpg can't handle that, I'm sorry but there's nothing I can do in cryptsync.

**Comment by artromone** [comment]
I see, thank you!

**Comment by artromone** [comment]
Have an Idea — CryptSync can transform Cyrillic to Latin, then run gpg, then rename file to Cyrillic. May be helpful.

**Comment by stefankueng** [comment]
or just don't use gpg for encryption?

**Comment by artromone** [comment]
Yeah, now I don't use it. So, the problem is solved. But for some people it may be a workaround.
