### ISSUE TITLE
Is there any config file which stores the settings of CryptSync?

### ISSUE THREAD

**Issue by purbam** [stefankueng/CryptSync#11]
Just started using this great tool, and I love it! Thank you!
I have many pairs to sync different directories on different disks to a backup area. It really took me quite a while to setup all these pairs. So I am wondering is there a config file to store these information? Maybe I should backup it as well in case I need reinstall the tool or even reinstall the OS.

**Comment by cfbao** [comment]
Settings are saved in the registry: HKCU\Software\CryptSync

**Comment by purbam** [comment]
> Settings are saved in the registry: HKCU\Software\CryptSync

Got it! Thanks a lot!
