### ISSUE TITLE
[Question] What happens if I cancel the sync process or quit the program during background sync?

### ISSUE THREAD

**Issue by COOLak** [stefankueng/CryptSync#110]
Let's say I'm syncing a very large amount of data (with encryption of everything including file names) to a webdav storage with a very low upload speed, and I don't want to keep my computer awake at night. If I cancel the sync process or quit the program during background sync, what happens? The next time I start the same sync task, will it have to start all over or will it just continue where it left off? Also, where does the program store the current sync progress?

**Comment by stefankueng** [comment]
CryptSync uses the last-modified timestamp of files to determine what to sync.
So it won't start over.
