### ISSUE TITLE
[Question] What happens if I mark "Start with Windows" but the drive with the original files won't be present?

### ISSUE THREAD

**Issue by COOLak** [stefankueng/CryptSync#111]
I'm syncing encrypted data from the encrypted hard drive which I first need to decrypt and mount. If I let CryptSync start with Windows and it doesn't find that drive (obviously, until I mount it), what happens? Will it think that I removed the original folder altogether and so will remove all my encrypted copies from the destination folder? Or not? How exactly is this scenario handled?

**Comment by stefankueng** [comment]
if the whole "original" folder is missing, CryptSync will try to restore the files in the original folder from the encrypted files. However since this also is not possible it would generate a lot of errors.
Basically: don't do that.
