### ISSUE TITLE
Spaces in source folder path don't create sub-dirs in target path

### ISSUE THREAD

**Issue by Horst12** [stefankueng/CryptSync#112]
I made an entry for a Thunderbyte local mail-dir
The full source path is 
C:\Users\horst\AppData\Roaming\Thunderbird\Profiles\eypx4io3.default\Mail\Local Folders-maildir
The target path is simply D:\backup\mail
There are no sub-dirs created in the target dir.
Enclosing the source path with "" doesn't help.
It only copies files from the source into the target.

**Comment by stefankueng** [comment]
subdirs are only created it they're not empty.
