### ISSUE TITLE
ERROR:   error accessing path

### ISSUE THREAD

**Issue by Todd1561** [stefankueng/CryptSync#113]
There's some kind of bug with the latest version 1.4.5.  I get "ERROR:   error accessing path "S:\Sites", skipped" when attempting to use a remote that's a UNC path, if I switch to a local directory it's fine.  If I downgrade to the previous release 1.4.4.462 it works fine.  There's no problem with permissions on the remote share, I can even browse to and navigate the remote folder from within CryptSync.

Thanks!  Great utility, excellent work on this project.

**Comment by stefankueng** [comment]
I can not reproduce this. Using a NAS as the remote.
Tried with mounted shares (e.g. K:\) and the UNC name (e.g. \\NAS1\dir1), both work fine for me.

**Comment by stefankueng** [comment]
ok, can reproduce it now...

**Comment by Todd1561** [comment]
Thanks for the quick resolution! What was the issue? Just curious.
