### ISSUE TITLE
File and folder deletions keep getting re-created instead

### ISSUE THREAD

**Issue by DeanoV6** [stefankueng/CryptSync#114]
Since installing the latest version, now, everytime I delete a file or folder, it keeps getting re-created a few minutes later meaning I currently can't delete anything.

**Comment by DeanoV6** [comment]
I've now confirmed that downgrading back to 1.4.4, the issue is not present.

**Comment by stefankueng** [comment]
I can not reproduce this. Works for me as expected.
Do you have a special setup maybe?

**Comment by DeanoV6** [comment]
Not that I’m aware of? I’ve reverted back to 1.4.4 and all is okay again now.

Dean

On 19 Jun 2024, at 19:44, Stefan Küng ***@***.***> wrote:

﻿

I can not reproduce this. Works for me as expected.
Do you have a special setup maybe?

**Comment by stefankueng** [comment]
I got now a setup where I can reproduce the problem.
Not sure how to fix this yet, but since I can reproduce the problem now it shouldn't take too long (I hope).

**Comment by DeanoV6** [comment]
Ok, thank you very much for taking the time to look into the issue.  (It’s an excellent utility by the way 🙂)

Dean

On 19 Jun 2024, at 20:19, Stefan Küng ***@***.***> wrote:

﻿

I got now a setup where I can reproduce the problem.
Not sure how to fix this yet, but since I can reproduce the problem now it shouldn't take too long (I hope).

**Comment by RKENS** [comment]
Hello. I'd like to reopen this conversation if possible. I have the same problem. I just installed the upgrade to 1.4.7.481 and it is still adding back files and folders that I delete every time a sync runs. If you can expedite a fix for this, it would be greatly appreciated.

Thanks,
Russ

**Comment by RKENS** [comment]
I tried reverting back to 1.4.4.482 and I still have the problem unfortunately. That's the oldest download that I still have so I guess I'll have to wait for a fix.

**Comment by Jimrc53** [comment]
Reverting to version 1.4.4.462 resolved this issue for me. Earlier versions can be found here... https://github.com/stefankueng/CryptSync/releases

**Comment by RKENS** [comment]
I have a download for v1.4.4 and I tried reverting to it, but it does the
same thing.

[image: image.png]

Thank you,

Russ

**Comment by Jimrc53** [comment]
Ouch.  I saw that you had tried a version of 1.4.4 on GitHub.  When I
reverted, I did an uninstall of 1.4.7 first before installing 1.4.4.

Hopefully, version 1.4.8 will come out soon with a fix.

Thanks,
Jim

**Comment by RKENS** [comment]
I also did an uninstall of 1.4.7 first like you. I too am hoping for a fix
in the new version because I do rely on the feature to encrypt my stuff
before sending it up to Google.

Thank you,

Russ

**Comment by stefankueng** [comment]
please provide the paths you want to sync.

**Comment by Jimrc53** [comment]
1.4.4.462 is working for me, so I am fine at this point.  In case it helps,
the paths I link are:
Original folder:  C:\Users\james\Documents\Private
Encrypted folder:  C:\Users\james\Google Drive\Private

I have "Sync file deletions" selected. (i.e. checked), and I use .7z as my
file extensions.
64-bit Cryptsync (CryptSync64-1.4.4.msi) is the file I reverted to, and it
does not have the issue.
64-bit Cryptsync (CryptSync64-1.4.7.msi) has the problem.
I also tried version 1.4.6... same problem as 1.4.7.
I did not try 1.4.5.

Thank you!
Jim

**Comment by RKENS** [comment]
[image: image.png]

I haven't checked all the folders listed above, but the Purchases folder is
where it has been a significant problem for me because I frequently add and
delete files and folders and also rename them. Any change I make now
results in a duplicate because the original comes back at the next sync.

Thank you,

Russ Kinch
Enterprise Network Systems, Inc.
