### ISSUE TITLE
How to update 7zip binary

### ISSUE THREAD

**Issue by bnkas** [stefankueng/CryptSync#12]
First, I want to say thank you for the great tool and all of your work on it. I have been using it for years and I love it. 

In the past, I used to periodically update the 7zip and gpg binaries by manually replacing them in C:\Program Files\CryptSync. I just updated to the new version and noticed that the 7zip binary no longer exists.

Is there a way to update the 7zip binary and make CryptSync use the updated 7zip binary? Or do we have to wait for a CryptSync update for  updates to 7zip?

Thanks.

**Comment by cfbao** [comment]
CryptSync no longer uses an external 7zip binary. It uses 7zip's code internally now. There's nothing you can update.

**Comment by stefankueng** [comment]
the 7zip code is now compiled into cryptsync directly, so there's no need to start a separate exe anymore.
