### ISSUE TITLE
User-triggered syncs may run concurrently with timer-trigger syncs

### ISSUE THREAD

**Issue by dansyl1** [stefankueng/CryptSync#124]
Multiple instances of CFolderSync will exist when the Options dialog is open:
- One created when CTrayWindow is instantiated
- One created when COptionsDlg is instantiated
Member variables such as m_bRunning and m_currentPath are specific to each instance. Thus, a user-triggered sync may run concurrently with a timer-triggered sync (TIMER_DETECTCHANGES or TIMER_FULLSCAN) on the same paths.

I propose to implement the following changes:
a) Add method to COptionsDlg to allow CTrayWindow to pass its m_folderSyncer.
b) Adjust CFolderSync::SyncFolders() to prioritize foreground syncs (do nothing if a foreground sync is in progress)
c) Arrange for sets created through notification of file change detection to remain untreated until the user-trigger sync is completed.

Proposed changes would not resolve this issue if multiple concurrent syncs are done by invoking CryptSync by command line (/syncall or /src and /dst).

**Comment by Jimrc53** [comment]
Hi dansyl1!
I understsnd less than 1% of your message.  (I am not very smart when it
comes to things like this!)

I can say that I do not invoke CyrptSync by command line. :)
I am a willing guinea pig if you or Stefan decide to send me a trial
version to try.

Thank you!
Jim

**Comment by dansyl1** [comment]
Sorry about lack of clarity. The CryptSync window can be opened using either the "Options" menu on the system tray icon or by starting CryptSync without the /tray option. A file sync triggered from the window (Sync files button, for example) may conflict by a file sync that CryptSync triggers periodically, as per "Interval for full scans in minutes" option, or if CryptSync detects file modifications. There is code in the CFolderSync class to handle possible concurrent execution but this code is not applicable in this case as two different instances of that class are created.  I proposed a solution for Stefan's comments. I will gladly implement the changes.
