### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by MSchreursHSO** [stefankueng/CryptSync#125]
When I run the installer (both versions) I get the following message:
This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package.

**Comment by stefankueng** [comment]
they work fine for me. Please check the digital signature. If it's not valid or doesn't show that the msi is digitally signed, then you have a corrupted download.

**Comment by MSchreursHSO** [comment]
Just checked it on another computer and there it does work, so problems is on my side. Thanks for the reply!
