### ISSUE TITLE
CryptSync 1.4.9 eats one core

### ISSUE THREAD

**Issue by StefanGrube** [stefankueng/CryptSync#133]
Since updating to 1.4.9 cryptsync (64 bit) often eats one core (~20%) cpu power. Neither traybar icon is usable nor app GUI could be shown or activated. Thread must be killed in task manager and app restarted, until issue happens again.
Stepping down to 1.4.8 this problem does not happen again.
Windows 11, 23H2, German, latest patches.

**Comment by Jimrc53** [comment]
I also had this experience with 1.4.9 (64-bit).  When it runs in the foreground, all seems to be OK... near zero CPU utilization.  However, when it runs as a background process, CPU utilization jumps up... to between 12-30 %.  I also reverted to 1.4.8. 
I tried to post a comment 3 days ago, but did not know how... Thankfully, StefanGrube opened this issue.

**Comment by NorTreblig** [comment]
Had the same problem on a freshly installed Win10 (version 22H2 x64 English, fully patched) with CryptSync version 1.4.9 x64.
I quickly reverted to 1.4.8 and everything's working normally.

It happened when running the application in background mode, but the 100% utilisation of one core didn't start right away:
It may have happened when the first file was changed or maybe when the full scan started.

Thank you for making CryptSync!

**Comment by dnalneh** [comment]
same issue here, win 11 pro newest version

anyway, thx for Cryptsync, best sync tool for me since ever :-)

**Comment by stefankueng** [comment]
I can't reproduce this problem.
What are your sync paths and settings?

**Comment by stefankueng** [comment]
can you try a build from here:
https://github.com/stefankueng/CryptSync/actions/runs/10329244175/artifacts/1797481097

**Comment by StefanGrube** [comment]
Hi Stefan,
here are my settings and paths. They are configured on 3 different machines, all Windows 11 23H2, German, 64bit.
CryptSync 1.4.9 fails on all 3 machines in the same way. 1 CPU core is used, trayIcon does not show tooltip, GUI could not be shown/activated by clicking on trayicon. cryptsync.exe must be killed in task manager.
![grafik](https://github.com/user-attachments/assets/f6e99b39-2306-4c18-aef1-dd87ecbe2695)
![grafik](https://github.com/user-attachments/assets/b247b494-532f-4571-822e-9def215e4fd2)
The Delphi path contains approx 8000 files.

**Comment by StefanGrube** [comment]
I've swapped the cryptsync.exe with the one provided by you yesterday.
I'll report in the next days what happens...

**Comment by dnalneh** [comment]
My source is a local folder and the target is a folder in Onedrive. So, I think I have the same settings like @StefanGrube 
Currently, I'm trying the build you have linked yesterday. I will report back on this.

**Comment by StefanGrube** [comment]
So far the new build of crytsync didn't act up again, memory consumption is ~5MB, cpu power 0% running in background.
System running now for ~12h, several power mode changes to standby/wakeup.

**Comment by stefankueng** [comment]
Thanks @StefanGrube for testing and reporting back. I'll make a new release then.

**Comment by StefanGrube** [comment]
cryptsync still going strong!
Have you been able to identify the issue in your code?

**Comment by stefankueng** [comment]
yes, the problem in the code is fixed. I figured that the bug could be the reason for this "eats one core" problem but I could not get it to do that on my machine. So thanks for confirming that this really was the source of this problem.

**Comment by StefanGrube** [comment]
I just saw the full sync cycle in the background, CPU power comsumption was max 5%.

**Comment by dnalneh** [comment]
issues are resolved for me also :-) thanks alot
