### ISSUE TITLE
HackTool/Win32.Qwerty

### ISSUE THREAD

**Issue by Benoit87** [stefankueng/CryptSync#14]
It seems that Virus total find a malware in CryptSync  (HackTool/Win32.Qwerty) . Any information about it?
Regards,

**Comment by cfbao** [comment]
A single detection out of 64 AV engines is almost always a false positive and never a cause for concern, especially for old files.
Usually, it's not until you get at least about 5-10 alerts should you be somewhat concerned.

To further assure you, the detection comes from "gpg.exe" bundled in CryptSync. This "gpg.exe" is exactly the same as the one distributed on GnuPG's official site.

You can check out GnuPG's official download location https://gnupg.org/ftp/gcrypt/binary/ and the file "gnupg-w32cli-1.4.22.exe". It bundles the exact same "gpg.exe".
You can also check the PGP signature. It's good signature from a [trusted member](https://pgp.key-server.io/pks/lookup?op=vindex&fingerprint=on&search=0x249B39D24F25E3B6).
![sig](https://user-images.githubusercontent.com/8552945/49237744-df4c5600-f3cc-11e8-9e68-bd2adb2ab546.png)

**Comment by stefankueng** [comment]
if the digital signature on the msi and exe is correct, then I guarantee that there's nothing to worry about.
