### ISSUE TITLE
Feature Request: Button "Sync Now"

### ISSUE THREAD

**Issue by jonnieZG** [stefankueng/CryptSync#17]
I am really missing a button "Sync Now", that would immediately trigger the Sync process, without exiting the program.

**Comment by cfbao** [comment]
![screenshot 2018-12-05 112951](https://user-images.githubusercontent.com/8552945/49528046-129a5380-f8ab-11e8-862d-50154dee1d47.png)

**Comment by jonnieZG** [comment]
Thanks for the info, that's what I wanted. Nevertheless, adding a button next to the "Run in Background", "Sync Files and Exit" and "Exit" would be intuitive.
