### ISSUE TITLE
error accessing path "XYZ", skipped

### ISSUE THREAD

**Issue by Bienie77** [stefankueng/CryptSync#27]
I just installed the new version 1.3.2 and now I get the error message above for any folder pairs I have. I even started it in administrator mode but still the error persists. Any ideas what the reason could be?

**Comment by stefankueng** [comment]
what are the exact paths you entered?

**Comment by Bienie77** [comment]
As an example "D:\Dokumente". But it was the same for "D:\Bilder" etc. I now sync pair by pair and it works but not for "D:\Dokumente". The popup "syncing folders/files" is displayed a long time for this pair but nothing happens. Not sure if that is the same error or a different one. I will let it run over night to see if it is only a time/speed issue

**Comment by Bienie77** [comment]
I am closing this issue. I could reproduce the error. I linked the cloud with an SMB directory in Windows. And when I haven't clicked on the drive before starting CryptSync it gives this error. The error message is a bit confusing because in actuality it is the cloud path that is the problem.
