### ISSUE TITLE
Unexpected confirmation dialog after choosing to run in background

### ISSUE THREAD

**Issue by hharmjanz** [stefankueng/CryptSync#28]
A message box has been added recently to prevent the user from accidentally exiting the tool.
However, this seems to have a side effect as the confirmation dialog is now also shown after the user has pushed the 'Run in background' button. I actually have to choose 'Yes' in a dialog asking me whether I want to quit in order to have the program running in the background - this is rather confusing, isn't it?

**Comment by Laserstrahl** [comment]
I can confirm the issue.

Repro:
Open the UI
Press "Run in Background" Button
![grafik](https://user-images.githubusercontent.com/59196077/71404779-bdef8500-2633-11ea-96ce-1068d17a70fd.png)
Textbox shows: "Are you sure you want to quit?"
![grafik](https://user-images.githubusercontent.com/59196077/71404841-df507100-2633-11ea-910a-8f617c839d45.png)

However it is not quitting, but closing the UI sending CryptSync to the tray.
