### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by ecostar** [stefankueng/CryptSync#29]
Windows 10 Pro.
Unexpectedly crashes when syncing

**Comment by 82ndab-Bravo17** [comment]
For me it seems to crash when syncing a large number of files, was that the same for you?

**Comment by Sjustein** [comment]
I have the same issue, windows 10 pro as well, also syncing a lot of files (some big files, but mostly very small < 5kb files). I have tested this on 2 different systems (windows 10 pro and home). 

Settings:
Syncing from a local network drive (by \\<ip>\folder path) to a local folder. I'm only syncing from unencrypted (network drive) to encrypted (local). My configuration uses GnuPG encryption and I do not encrypt filenames.

When trying to restart cryptsync a few times, after some time windows completely locks up as well and the only thing that fixes this is a hard reset. To be clear: I suspect this originating from cryptsync, but I haven't been able to verify it. The log doesn't show anything special.

**Comment by vitaliyg2** [comment]
Same issue for me, using current version 1.4.0 64-bit . During sync of big folder program just terminates with message "Windows encountered an error and program will be terminated", nothing about the error is stored in the log.
Here is the entry from Event log:
```
Faulting application name: CryptSync.exe, version: 1.4.0.427, time stamp: 0x60abcddd
Faulting module name: ntdll.dll, version: 6.1.7601.24545, time stamp: 0x5e0eb67f
Exception code: 0xc0000374
Fault offset: 0x00000000000bf262
Faulting application path: C:\Program Files\CryptSync\CryptSync.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
```

Exception code seems to be indicating heap corruption.
