### ISSUE TITLE
Feature Request: Block Exit Button

### ISSUE THREAD

**Issue by joeschwarz** [stefankueng/CryptSync#3]
Hello,

I am using your tool here at home. Sometimes I klick on the exit-button instead of run in background button. Would it be possible to block the exitbutton that there is no way to switch off the tool for accident?
Just a menuitem "Show Exitbutton?  Yes[] No[]

Thanks to all!

**Comment by ScottRFrost** [comment]
I think a "Are you sure you want to exit CryptSync yes / no" confirmation would probably be cleaner than a new option.
