### ISSUE TITLE
Cannot exclude subfolders from sync

### ISSUE THREAD

**Issue by vinnic62** [stefankueng/CryptSync#31]
Hi,

I've created a folder pair as such: 
Original Folder --> d:\folder1
Encrypted Folder --> f:\folder2

Then I entered the following for files I did not want synced at all because I wanted certain subfolders of folder1 to be ignored altogether:

![Files to ignore](https://user-images.githubusercontent.com/59870097/72401343-d1f45580-379f-11ea-9472-a6d54ef6d211.jpg)

However, cryptsync still synced and encrypted subfolder1, subfolder2 & subfolder 3.

How can I exclude complete subfolders from the cryptsync syncing process?

Thanks.

**Comment by stefankueng** [comment]
this works fine for me: adding the full path of the folder with `\*.*` at the end ignores that folder, including all subfolders of the ignored folder.

Are you sure you entered the path correctly?

**Comment by vinnic62** [comment]
Hi Stefan, thank you for your reply.

It seems to me that the problem occurs when I edit an existing pair to add subfolders I don't want synced. Therefore, the pair when first created syncs the subfolders because I don't exclude them from the sync. However, they continue syncing even after I edit the pair to specify that I don't want the subfolders synced any longer.

**Comment by stefankueng** [comment]
if you edit a sync pair to exclude files that are already synched, you might have to restart cryptsync. Not sure, but when I tried this it worked fine for me, even without restarting.

**Comment by vinnic62** [comment]
Ok. I didn't restart cryptsync after editing the pair. I eventually got around the issue by deleting all pairs and creating new pairs (with files I did not want synced) with new sync folders. Basically restarted from scratch. Everything works as expected now.
