### ISSUE TITLE
Have to continuously delete & recreate pairs

### ISSUE THREAD

**Issue by vinnic62** [stefankueng/CryptSync#33]
Hi Stefan,

I've been finding myself deleting pairs and later recreating them when I want the sync process to resume. Therefore, I have a suggestion. Would it be possible to have an option to temporarily suspend or pause a pair, and once paused, the option to restart a pair when ready to resume syncing? 

One possible use of the feature I describe is perhaps having a pair for decryption that is only turned on when needed.

**Comment by Reemmoo** [comment]
That would be a very helpful feature. Especially for large amounts of data that don't change often
