### ISSUE TITLE
Confusing message

### ISSUE THREAD

**Issue by vinnic62** [stefankueng/CryptSync#34]
Hi Stefan,

I have set up a pair with the following settings:
![Cryptsync pair settings](https://user-images.githubusercontent.com/59870097/72767090-fa200080-3c46-11ea-8d11-6bbdc6b308d8.jpg)

What does it mean to get a message like the following?
INFO:    counterpart of file FILENAME does not exist in src folder, delete file

It's true that FILENAME does not exist in the unencrypted folder, but FILENAME is not deleted from the encrypted folder.

**Comment by 82ndab-Bravo17** [comment]
See my issue #30 for an explanation of a bug when using a root folder for either source or destination. I suspect that if you look closer you will see that "INFO: counterpart of file FILENAME does not exist in src folder, delete file" is actually "INFO: counterpart of file ILENAME does not exist in src folder, delete file" ie it is missing the first character of the pathname.

**Comment by vinnic62** [comment]
Thank you 82ndab-Bravo17, you are absolutely right. Everything works as expected when I don't use a subfolder.
