### ISSUE TITLE
Rename ZipFiles result Error fail to set file time

### ISSUE THREAD

**Issue by ThomasL1969** [stefankueng/CryptSync#38]
We use cyprtsync to backup and restore Windows Userprofile Folder. 
In a migrationstep we need to rename some zipped Files. 
Wenn decrypt a file that has been renamed as a zip file , the error occurs :
decrypt file \\...... to C:\users\user1\Documents\blafile.doc
ERROR:   failed to set file time on  C:\users\user1\Documents\blafile.doc

**Comment by stefankueng** [comment]
Well, the filenames must match. You must not rename them. Or rename them back for the decryption to work.
