### ISSUE TITLE
CryptSync 1.1.4 encrypted all (3) pairs again

### ISSUE THREAD

**Issue by bttrx** [stefankueng/CryptSync#40]
Hi!

I'm aware that CryptSync 1.1.4 on Windows XP is unsupported now, but nevertheless I would like to ask the following:
In early May I installed CryptSync and created three pairs with local folders on my XP machine.
Encryption worked without problems, but on May 24th 30 minutes after I started XP and (automatically) CryptSync, CryptSync began encrypting all files again, although they didn't change. The 'last write time' of the files is still the same.

The log file says:
```
05/24/20 14:30:00 : Starting CryptSync
05/24/20 15:00:00 : encrypt file D:\Backup\DIA\4DSD.ZIP to D:\CryptSyncCloud\DIA\4DSD.ZIP.cryptsync
05/24/20 15:00:01 : encrypt file D:\Backup\DIA\ALADDIN.PAT to D:\CryptSyncCloud\DIA\ALADDIN.PAT.cryptsync
05/24/20 15:00:01 : encrypt file D:\Backup\DIA\ALADDIN.ZIP to D:\CryptSyncCloud\DIA\ALADDIN.ZIP.cryptsync
...
```
I would have expected the log saying something like "encrypted file is older".

Any idea, why this happened?

Cheers,
Robert

**Comment by stefankueng** [comment]
If something on XP doesn't work right, it's most likely because your PC belongs to a botnet now.
You really, really should not use XP anymore under any circumstances!
That said: try the checkbox "FAT file system workaround" in the pair settings.

**Comment by bttrx** [comment]
Two years later: XP didn't belong to a botnet (and still doesn't), but I had moved the `DIA` folder from `D:\CryptSyncCloud\` to another folder by a drag'n'drop "accident". So, CryptSync was right to encrypt all files again.
