### ISSUE TITLE
Assistance with how to compress only and not encrypt large files

### ISSUE THREAD

**Issue by greavette** [stefankueng/CryptSync#41]
Hello,

Thank you for making CryptSync available.  Very nice program for cloud backup.

I have a usecase where I want to use CryptSync locally and backup a database .bak file to another server (folder) on my local network. I don't want to encrypt this backed up file but I do want to compress it.  How can I use CryptSync to copy a .bak file to my destination folder and only compress it?  My .bak files are approximately 16GB in size.
Also, where is the working folder to compress files before they are copied to the destination folder?  Can I modify CryptSync to specify where this working folder is?

Thank you.

**Comment by stefankueng** [comment]
you can leave the password empty.

**Comment by greavette** [comment]
Thank you @stefankueng for you comment.  I apologize for the delay in responding to your post.  

Does CryptSync also allow for simple sync of two folders whereby no .7z or .cryptsync extension is added?  I have an other usecase where I'd like to simply sync two folders to be exactly the same (no change in extension).  Is this possible?

Thank you.

**Comment by stefankueng** [comment]
under "enter files you don't want encrypted but copied below", enter *.* in that box.

**Comment by ghrasc** [comment]
This is achieved by entering
`*.*`
into "files you don't want encrypted but copied"

P.S. duplicate to my answer in #67 just in case s/o looks for the answer here 1st
