### ISSUE TITLE
Feature Request: Ignore folders - mask

### ISSUE THREAD

**Issue by Reemmoo** [stefankueng/CryptSync#44]
Like the ignore mask for files, a igrnore mask for folders would be very helpful to avoid sync with some folders.
For example: archive*¦backup*¦temp¦windows¦_*¦ etc.

**Comment by stefankueng** [comment]
the ignore mask isn't just for files, it also ignores files if the ignore pattern matches any part of the full file path.
So you can enter your example as is and it will work. However: you have to use the | char to separate the items, not the ¦ char
