### ISSUE TITLE
Is it possible to choose an (unknown) extension other than .7z and .cryptsync?

### ISSUE THREAD

**Issue by ElTopo** [stefankueng/CryptSync#45]
Hello,

I don't really want to use a well-known file extension such as .7z or .cryptsync, they are somehow implying the data is encrypted by 7Zip/CryptSync. I prefer a user-custom string, for example .xyz1abc.

Is it possible?

**Comment by stefankueng** [comment]
sorry, no.
And I think this use case is too specific to be implemented.
