### ISSUE TITLE
Avoid full scann

### ISSUE THREAD

**Issue by Reemmoo** [stefankueng/CryptSync#47]
I have over 200,000 files, that's over 200 GB of data, which I want to synchronize.
How can I prevent the full scan or set it to only be triggered manually?

**Comment by stefankueng** [comment]
you can configure the full-scan interval. Just set it to a very high number of minutes.

**Comment by Reemmoo** [comment]
Hi Stephan

the max I can set are 999 minutes. That means, that every 16.5 hours the full scan starts again. I have a lot of data. The full-scan actualy runs arround 7 hours...
Maybe you can add one or two digits more? 9999 or 99999 would better :-)

In my opinion there should be a way to prevent the full scan. I have a lot of problems with OneDrive, just because the full scan regularly rewrites all data and sets a new timestamp, even the data has not changed. 

The automatic full scan works fine for small amounts of data. For large amounts of data this is not useful and should be possible to be turned off.

Thank you
