### ISSUE TITLE
CryptSync does not work with SUBSTed drives

### ISSUE THREAD

**Issue by RieksJ** [stefankueng/CryptSync#5]
I found that when I map a directory onto a drive letter in Windows 10, using
~~~
subst f: c:\dir1\dir2\dir3
~~~
and I want to CryptSync a directory in `f:`, then CryptSync stops working:

<img width="267" alt="cryptsync has stopped working" src="https://user-images.githubusercontent.com/8522589/40643513-b1407b98-6320-11e8-8b72-e47fe6a50274.PNG">

The log file only contains 'INFO' statements (that make sense), so that does not provide any help as to why this happens.

**Comment by stefankueng** [comment]
`f:` is not a valid path.
Use `f:\` instead.

**Comment by rj2002060** [comment]
Do you think it is appropriate for CryptSync to stop working because `f:`is not a valid path?

**Comment by stefankueng** [comment]
no, that's why the issue is still open.
