### ISSUE TITLE
Cannot add ignore string

### ISSUE THREAD

**Issue by justmeonthegit** [stefankueng/CryptSync#52]
According to documentation add a ignore string to the box can be done by entering the string or add by paremeters:

I want to ignore everthing from the recycle.bin
So the command will be:
CryptSync.exe /ignore:"*.tmp*|~*.*|thumbs.db|desktop.ini|$recycle.bin/*"
The textbox in the GUI is then NOT displaying this.

Editing the string in the textbox is oke. I did not test if it works but after exit from the tool the default string is being seen.

How to solve this?

**Comment by stefankueng** [comment]
For command line parameters to work, you also must specify an /src and /dst parameter. Without those, all other settings are ignored.
