### ISSUE TITLE
Handling "decryption failed" situations, getting more information?

### ISSUE THREAD

**Issue by amstelje** [stefankueng/CryptSync#54]
Hi,

_Not sure if this is a bug of feature request. Let me know if I should ask/report somewhere else._ 

Upon decrypting an 800MB outlook pst file (for back up restore), the decryption fails. It progresses nicely, the file size grows, but at the end the log file reports that the decryption failed. The log file doesn't give that much information of what has failed.

Is there a way to get more log information? Or even better, keep the decrypted file despite it "failed". Maybe I can recover a major portion of the restored file.
Of is there a separate tool which could help recovery of the file?

**Comment by stefankueng** [comment]
you can try to decrypt the file with 7zip, maybe you'll get more info with that.

**Comment by amstelje** [comment]
Have tried it, but in this case the pair was setup with GnuPG. So with 7zip it doesn't work.

**Comment by amstelje** [comment]
Noticed that the decryption of the gpg files is done with the gpg command line exe. Managed to get the decryption started, but it appears that files are having errors. 

> Example output of the command line decryption:
gpg: CAST5 encrypted data
gpg: encrypted with 1 passphrase
gpg: no valid OpenPGP data found.
gpg: block_filter 00FEE910: read error (size=11890,a->size=11890)
gpg: Problem reading source (890702227 bytes remaining)
gpg: handle plaintext failed: file read error
gpg: WARNING: message was not integrity protected
gpg: block_filter: pending bytes!

But, the good thing is that when decrypting with the command line, the decrypted file remains available. Which is exactly what I needed and managed to get a major part of data back. 
But, it appears that all the backups of this about 800MB pst are crippled. Is there anything that went wrong with the setup or are we using a wrong configuration? And do you have suggestions to further decrypt the files?

**Comment by stefankueng** [comment]
The problem with pst files is that they're usually opened in Outlook, so when you sync those files while they're open, they get changed while being encrypted - which then cripples the result.
So I recommend to not sync pst files automatically but only manually.
