### ISSUE TITLE
a bug with auto sync

### ISSUE THREAD

**Issue by aecra** [stefankueng/CryptSync#56]
I set a pair with '*.md|*.markdown' in 'Enter files you don't want encrypted but copied below'. But when I add to the original folder a markdown file named 'a.md', there will be a folder named 'a.md.cryptsync' in Encrypted folder with the markdown file in it. And when I point the 'Syne files', the file in this folder will be removed and it appears at the Encrypted folder.

**Comment by aecra** [comment]
I test out that only after the function starts and then I add file it will appear this situation. And it only appears at the first sync when 'SyncFolders' will not run. I think the bug is in 'TrayWindow.cpp'. But I haven't learned window coding. Can you check what's wrong?

**Comment by stefankueng** [comment]
just FYI: you have to set the pair with "*.md|*.markdown" - note the '*'
