### ISSUE TITLE
Allow to configure which files to compress and which only to encrypt

### ISSUE THREAD

**Issue by TimurBorn** [stefankueng/CryptSync#6]
Hello,

it seems that v1.31 (and v1.27_342) do not use any compression at all. I checked with several files (txt, Outlook PST, Lightroom catalog).

For the time being I am back to v1.27, which seems to use a somewhat weird mixture of compression ratios (LZMA2:26 on a smaller PST, but only LZMA2:19 on a larger one that would benefit more from better compression). Still better than no compression at all. ;)

**Comment by stefankueng** [comment]
v1.31 uses compression. But only for files smaller than 100MB.

**Comment by EiniStein** [comment]
Thanks for the quick answer. Turns out that I meant v1.30, not v1.31.

I will keep using v1.27 then, because it uses only half the space on my Dropbox account (especially compressing those big PST and Lightroom catalog files helps a lot).

**Comment by stefankueng** [comment]
Sorry, I meant v1.30 as well.
It does compress the files for me.
How big are your PST and Lightroom catalog files?

**Comment by EiniStein** [comment]
Here are some examples of big files and what v1.27 compresses them to:

PST 1: 103 mb -> 72 mb LZMA2:14 (47 mb using 7Z "normal" LZMA2:24)
PST 2: 71 mb -> 25 mb LZMA2:26 (37 mb using 7Z "normal" LZMA:24)

LR 1: 188 mb -> 51 mb LZMA:14 (36 mb using 7Z "normal" LZMA:24, 48 mb using 7Z "fastest" LZMA:16)

**Comment by EiniStein** [comment]
I checked again: small files are indeed compressed. Maybe v1.27_342 did not compress them (and then v1.30 had no reason to update them)?

Still I prefer compression for big files, too, so I will stay with 1.27 for the time being. Overall I would prefer if we could just define file-types that we don't want compressed, independent of size.

Thanks and regards!

**Comment by stefankueng** [comment]
So I think this issue should be about the ability to configure which files get encrypted only and which ones also get compressed.
This should be implemented so that a specific size can disable compression (e.g., bigger than 100MB) but also per file extension (e.g., jpg/png/mp4 don't need compressing because they already are compressed).

**Comment by EiniStein** [comment]
Yes, encryption is useful in any case, compression is useful for those files that benefit most from it.

Frankly compressing many very small files can take more time than compressing one big file, especially if the space savings are minimal. Compressible big files are the most relevant files when it comes to compression.

So I see compression exclusion by file extension and/or folder (to exclude precompressed files) as the more useful option.

**Comment by TimurBorn** [comment]
Hello again.

I managed to build CryptSync from the source-code, trying to implement all the raw image file extensions. Unfortunately it seems that the "std::wstring orig_ext = CPathUtils::GetFileExtension(orig);" part of the 1.27 fork does not work. Extensions like "JPG" and the like are still compressed, so the "if" expression does not seem to do what it's supposed to do.

Now I am trying to get this work, even though I am not a coder. Any hint would be appreciated.

**Comment by TimurBorn** [comment]
I installed your pre-build binaries for 1.27 again and checked on JPG files again. Indeed it *does* use compression on JPG files despite the IF clause being meant to set "compression = 0". So some part of the IF does not work, maybe the GetFileExtension part to begin with?!

**Comment by TimurBorn** [comment]
Sorry, I only now realized that I was working with a personal fork of 1.27 from another user. So the GetFileExtension solution was his work. I will try to wrap my head around how to disable compression for certain extensions. Again, any hint is welcome.

**Comment by TimurBorn** [comment]
Indeed it turned out to be a case of upper vs. lower case hardcoding. With that knowledge I will be able to code in my own list of extensions. Thanks for the hint cfbao.
