### ISSUE TITLE
Update command line help text with missing parameter

### ISSUE THREAD

**Issue by alrahman** [stefankueng/CryptSync#60]
Command line help text does not document compresssize parameter

**Comment by alrahman** [comment]
I added a comment on the commit, maybe it was missed.

The parameter is /compresssize but you added /compress.

Which brings me onto another thought: should the parameter names be stored in 1 place to make it easier to add/amend?

**Comment by stefankueng** [comment]
https://github.com/stefankueng/CryptSync/commit/80c1656df4640575a27e3ef4b7e15efdb3e9a65a
