### ISSUE TITLE
Using base4k for file name encryption

### ISSUE THREAD

**Issue by raingros** [stefankueng/CryptSync#62]
Really like CryptSync, great piece of software!

Unfortunately, I‘m running into the file name length restriction when using file name encryption and syncing to OneDrive.

Any plans to integrate base4k (https://github.com/secomba/base4k) for file name encryption?

Cheers!

**Comment by stefankueng** [comment]
base4k is not really encryption because anyone can 'decrypt' the string in a few seconds...

**Comment by raingros** [comment]
Okay, so what I really meant was using base4k as encoding for CryptSync's file name encryption.

**Comment by stefankueng** [comment]
I get that. But now the filename encryption is a real encryption using the password used for encrypting the content.
this base4k "encryption" does not use a password, so it's basically an enhanced rot13...

**Comment by raingros** [comment]
Boxcryptor does it by encrypting the filenames with AES-256 and in a second step encoding this "encryption result" with base4k. Maybe you'd like to reconsider doing it the same way. Just a suggestion. :)

**Comment by stefankueng** [comment]
ok, that seems doable.
The only question now is how to handle sync pairs that use the current name encryption. Any ideas or suggestions?

**Comment by raingros** [comment]
From my standpoint as a non-developer I'd say the best solution would be to decrypt and re-encrypt and encode these filenames. Guess some sort of migration routine has to be implemented. But of course, the disadvantage would be that all files from the sync pair needed to be synced again. 

Alternatively, CryptSync could use base4k only for new pairs and retain the old filename encryption scheme for older pairs.

I'd prefer the former, because it would be a clean cut, but maybe existing users which sync pair needed to resynced completely may think different.

**Comment by raingros** [comment]
I'm not sure, but maybe it's also possible to just encode the existing decrypted file names to base4k. I tested to encrypt an encrypted folder name with 46 chars (d1be625d4ceeb089310391bd449123474366d40f4460df) and the base4k encoder gave me 31 chars back (晃慢晓昲捖搴昶敥昣怸掓挱挃挹挖扤捃搹挓戳捃朴挳昶晃搰晣搴捣恤䁦).

In this case you could simply add another option to encode the encrypted filenames with base4k to the options.

Of course that doesn't solve the problem that all files needed to be resynced when base4k is applied, but this could simply be addressed by triggering a warning to the user that activating base4k encoding for an existing pair requires a full resync.

Cheers!
