### ISSUE TITLE
Upload bandwith usage issue

### ISSUE THREAD

**Issue by mbdaso** [stefankueng/CryptSync#65]
CryptSync v1.3.5.416 takes all my available upload bandwith, I have performed a speedtest closing and opening the tool and saw the difference. 
I'm using it with OneDrive.

**Comment by stefankueng** [comment]
CryptSync does not use bandwidth, it synchronizes two folders. However if one of those folders is a cloud drive folder, then of course all data there is synched to the cloud, and that uses bandwidth.
For onedrive, you can configure it to not use all available bandwidth in the settings.
