### ISSUE TITLE
Copying files from Source to Destination without compressing - Not working to add a . to "enter files you don't want encrypted but copied below"

### ISSUE THREAD

**Issue by greavette** [stefankueng/CryptSync#67]
Hello,

I'm re-opening this issue as I've recently noticed that my files moved to the destination folder once again have a .7z added to them. My hope was to move files as is and not compress them.  

I had opened this issue previosly:

https://github.com/stefankueng/CryptSync/issues/41

In that issue the solutino was to add the following:

under "enter files you don't want encrypted but copied below", enter . in that box.

I've ensured this . was added to this box but I now notice that my files coped to their destination have a .7z at the end of them.  I've upgraded my CryptSync to 1.4 and have the same issue on that version as well.

Plesae assist with what's needed to copy files from source to destination and not compress them.  If possible could we have a checkbox instead to specify that we don't want to compress files and simply copy them as is.

Thank you.

**Comment by ghrasc** [comment]
in 1.41 I achieve that by entering *.* into "files you don't want encrypted but copied"

**Comment by ghrasc** [comment]
Ha, ha, ha, 
Github got stefankueng and me :)
When entering a single asterisk in comment text it is not displayed.

So you need to enter 
`*.*`
into "files you don't want encrypted but copied"

**Comment by greavette** [comment]
Thank you @ghrasc for this response.  Very much appreciate your help!  

I've adjusted my options to add a `*.*` now. I've confirmed that the sync now works to copy without compressing my file.

Cheers!

**Comment by ghrasc** [comment]
found out today that \*.\* is only half the truth:
That setting still compresses files w/o ending (like C:\Windows\systerm32\drivers\etc\hosts ).
The correct setting was a single Asterisk "\*".

HTH!

P.S. One writes an Asterisk here by 'escaping' it, so it's `\*` to display a single Asterisk like \*.
