### ISSUE TITLE
Feature request: Add option to split files that are larger than 4 GiB

### ISSUE THREAD

**Issue by DerFranke** [stefankueng/CryptSync#69]
Background: My Cloud-Provider only supports WebDav to access files without the official sync-client. But WebDav cannot transfer files, that are larger than 4 GiB.

It would be nice to have an option to split the files, before putting them into the encrypted folder.

**Comment by ghrasc** [comment]
+1 (especially as it's only a command line parameter to the 7z module so I guess it's the same in case CS calls an API)
`-v{SizeInByte}`

command line would look like
`7z.exe a -t7z -v2000000000  MyArchive.7z MySourceFiles`
to split into 2GB archives.
