### ISSUE TITLE
Original folder desciption is broken

### ISSUE THREAD

**Issue by weltenbeweger** [stefankueng/CryptSync#75]
in the "Sync Pair" Window (Version 1.4.3.466) the "Original folder" an the "Don't compress files...." Description is not fully visible if you have used the recommended screen scaling on Windows notebooks 125% or 175% but not at 100% or 150% . 

![SyncPair](https://user-images.githubusercontent.com/89711746/147981874-819a14e5-6e82-4b47-8df8-4306a3420c14.png)

**Comment by stefankueng** [comment]
works fine for me
![image](https://user-images.githubusercontent.com/665591/148270709-524d23c5-0725-4dbb-990b-b35c9866e1d3.png)

**Comment by weltenbeweger** [comment]
Hello stefankueng,

sorry, I forgot to inform you that the problem only occurs when CryptSync gets started / has to be restarted after the Windows screen scaling has been set to 125% or 175%.
Here are the steps with which I was able to reproduce the problem on 3 different hardware computers (no VM) each time.

1. Exit CryptSync
2. Open Windows Settings / System / Display / "Scale and  layout" and change the scale value to 125 or 175%
3. Restart CryptSync

I know it's not a big problem, but if someone's resolution is set to 125% by default, as is the case with me, they can't tell which unit is meant for the file size.

![125Percent](https://user-images.githubusercontent.com/89711746/148294191-d18fe496-4e40-4967-88c0-7a144583751c.png)

**Comment by stefankueng** [comment]
thanks for all the details on how to reproduce this. I was now able to reproduce the problem.
The problem however is that this is a problem with Windows itself: it does not calculate the control widths correctly if the scaling does not match the monitor. I'm guessing a rounding error.

I can 'fix' this by extending the widths of the controls by one 'device independent pixel'.
