### ISSUE TITLE
feature request: choose subdirectories to exclude

### ISSUE THREAD

**Issue by AmirrTAU** [stefankueng/CryptSync#78]
Hi, thanks for your great software. been using for years.
 I would like some certain subdirectories (out of many) to be synced with encryption and some without. is it possible to mark subdirectories for exclusion from the encryption stage ? if not, can you add it to the next version ?

**Comment by stefankueng** [comment]
"enter files you don't want synced below" - enter the folder name there

**Comment by playmobilmeister** [comment]
For the sake of anyone encountering this - don't put any spaces before or after the '|' seperators. otherwise they **will** be encrypted !
