### ISSUE TITLE
New Feature - Icon Change when sync fails

### ISSUE THREAD

**Issue by ToRuDev** [stefankueng/CryptSync#82]
Hello @stefankueng , 

Thanks for your useful tool.

Could it be possible to change the Tray Icon when/if a sync fails ?
I think of putting an Exclamation Mark on top of it for ex.

Thank again for all your work.

**Comment by Kaligula0** [comment]
It would be very very very useful if the icon showed any information! Something like Dropbox does. Ideally it would show OK/syncing/FAIL statuses. But at least "FAIL" would be handy. Please :)

**Comment by Kaligula0** [comment]
And maybe not only icon, but a notification (about FAIL), too?

**Comment by Kaligula0** [comment]
Thank you, @stefankueng! :)
