### ISSUE TITLE
Can CryptSync write to Windows Event Viewer?

### ISSUE THREAD

**Issue by greavette** [stefankueng/CryptSync#88]
Hello,

I'm interested in monitoring my CryptSync with Zabbix.  My thought is to have CryptSync write errors (or anything really) to Windows Event Viewer.  Is this possible to have Cryptsync write to Windows Events?

Or another question...I'm looking in ErrorMsg.cpp and I see the following messages.  Are these the type of errors I should be looking for:

    // case ERROR_NO_MORE_FILES   : s = "No more files"; break;
    // case ERROR_DIRECTORY       : s = "Error Directory"; break;
    case E_NOTIMPL             : s = "E_NOTIMPL : Not implemented"; break;
    case E_NOINTERFACE         : s = "E_NOINTERFACE : No such interface supported"; break;
    case E_ABORT               : s = "E_ABORT : Operation aborted"; break;
    case E_FAIL                : s = "E_FAIL : Unspecified error"; break;

ERROR|Error|ABORT|FAIL

Thank you.

**Comment by stefankueng** [comment]
while it is possible to write to the windows event viewer, I'm sorry to say that I won't do that.
