### ISSUE TITLE
Slow unpack read-only files

### ISSUE THREAD

**Issue by Argimko** [stefankueng/CryptSync#92]
Hello Stefan, thank you for your very useful tool!

I just found a bug, I think.

Lets assume you have 20 small text files at `SOURCE` folder: 10 file _with_ set attribute **read-only**, and 10 files _without_ this attribute.

So, lets encrypt this with the command:

`"%PROGRAMW6432%\CryptSync\CryptSync.exe" /src:"SOURCE" /dst:"ENCRYPTED" /pw:"PASSWORD" /mirror /progress`

So it is OK, it works fast.

Now, lets clean up folder `SOURCE` and run the next command:

`"%PROGRAMW6432%\CryptSync\CryptSync.exe" /src:"SOURCE" /dst:"ENCRYPTED" /pw:"PASSWORD" /mirrorback /progress /logpath:"PATH_TO_LOG"`

So you will see that files _without_ attribute read-only unpack very fast, but files with **read-only** attribute unpacking about 10 times slowly. Also you will find at log-file, errors for read-only files:

`ERROR: failed to set file time on D:\Desktop\from\1.txt`

I would be very grateful to you if you can speed up unpack operation by fixing setting file time for read-only files.

Thank you!

I used CryptSync v1.4.3.446 on Windows 10 v21H2

**Comment by stefankueng** [comment]
this is already improved. See the
`#if 0`
section here:
https://github.com/stefankueng/CryptSync/blob/main/src/FolderSync.cpp#L1204

That section was responsible for the slow unpack.
