### ISSUE TITLE
How to build this app for Linux -if possible?

### ISSUE THREAD

**Issue by m-primo** [stefankueng/CryptSync#94]

**Comment by stefankueng** [comment]
It's not possible to build cryptSync for Linux since it uses a few Windows specific APIs.

**Comment by shubham2110** [comment]
@stefankueng  Could you please help me give a starting point on creating a simple service this this one for linux?

**Comment by m-primo** [comment]
> @stefankueng Could you please help me give a starting point on creating a simple service this this one for linux?

I think a starting point would be determine the Windows APIs that's used and then look for its compatible in linux.
