### ISSUE TITLE
password update

### ISSUE THREAD

**Issue by Xddass1** [stefankueng/CryptSync#95]
Hi, 
first, let me thank you for this app and your effort, it looks great 
I'm trying to evaluate the app to sync an encrypted copy to my onedrive, 
i couldn't update the password effectivally, after changing it the files aren't getting re encrypted, 
is that who it is supposed to work? 
do i need to delete the pair and recreate using a new password ? 

thanks

**Comment by stefankueng** [comment]
stop CryptSync (if running in the background), then delete all the encrypted files. Then start CryptSync again.
That will re-encrypt all files again with the new password.

It doesn't do this automatically because the files themselves did not change, only your password.
