### ISSUE TITLE
[v1.4.4.462] blank icon in SysTray

### ISSUE THREAD

**Issue by Kaligula0** [stefankueng/CryptSync#99]
After the update from recent (1.4.3) to newest (1.4.4) version (which includes icon changing according to sync status) there's no visible icon in SysTray. There's a place where it should be visible, also the tooltip and the right-click menu work; but the icon is invisible.

![image](https://user-images.githubusercontent.com/3950811/210137965-1f1b3424-5577-458f-90ca-302b7bc7d790.png)

Happens on 2 computers with Windows 7. Persists after reboot. Should I provide any additional information?

**Comment by Xddass1** [comment]
same here, several Windows 10 and 11

**Comment by DeanoV6** [comment]
I'm seeing this too.  Windows 10.

**Comment by stefankueng** [comment]
Duplicate of #98
